### ISSUE TITLE
Build error on openSUSE 13.1,13.2, SLE 12

### ISSUE THREAD

**Issue by rombert** [apache/incubator-pagespeed-mod#1313]
When upgrading from 1.9.32.11 to 1.11.33.2 I get link-time ( I think ) errors on older SUSE versions.

Here's a relevant snippet from the build log

```

[  707s]   LINK(target) out/Release/mod_pagespeed_speed_test
[  708s]   COPY out/Release/libmod_pagespeed.so
[  708s]   TOUCH out/Release/obj.target/build/mod_pagespeed.stamp
[  708s] out/Release/obj.target/third_party/serf/../../serf/third_party/serf/instaweb_ssl_buckets.o: In function `serf_ssl_check_host':
[  708s] instaweb_ssl_buckets.c:(.text.serf_ssl_check_host+0x46): undefined reference to `X509_check_host'
[  708s] collect2: error: ld returned 1 exit status
[  708s] make: *** [out/Release/mod_pagespeed_test] Error 1
[  708s] make: *** Waiting for unfinished jobs....
[  710s]   LINK(target) out/Release/mod_pagespeed_speed_test: Finished
[  710s] error: Bad exit status from /var/tmp/rpm-tmp.wLZhnK (%build)
```

You can also see
- [All the build results on SUSE distributions](https://build.opensuse.org/package/show/home:robert_munteanu:branches:Apache:Modules/apache2-mod_pagespeed)
- [Full build log for openSUSE 13.2 x86_64](https://build.opensuse.org/public/build/home:robert_munteanu:branches:Apache:Modules/openSUSE_13.2/x86_64/apache2-mod_pagespeed/_log), including all available RPMs

**Comment by crowell** [comment]
what version of openssl are you linking against.

IIRC that symbol is available in 1.0.2 and and higher.

**Comment by crowell** [comment]
If you need to be able to build with older versions of openssl, you'll need to patch a check in the x509 host verification.

https://www.openssl.org/docs/manmaster/crypto/X509_check_ip.html

Patching in the check is a bit tricky, so if you're able to require 1.0.2, then that's ideal. If not, let me know, and I'll take a look at what is required for a patch.

**Comment by rombert** [comment]
openSUSE 13.{1,2} have openssl 1.0.1, while SLE 12 has openssl 1.0.0 . 

I am not familiar with the pagespeed build, but would it be possible to skip building the test artifacts? we don't run then on the openSUSE build server instance, just a `make BUILDTYPE=Release`

**Comment by crowell** [comment]
the certificate checking isn't just used for tests. it's used in the https fetching infrastructure.

**Comment by rombert** [comment]
Ah, I see. Then a patch looks like to only way out. Unfortunately I know too little C/C++ to be of use here. If you'd be able to provide a patch it would be great.

**Comment by crowell** [comment]
RM'd

**Comment by crowell** [comment]
https://gist.github.com/507678b6b180dab203fc6c0756230855 patches in the functionality from the latest version of openssl. It's untested though.

**Comment by jeffkaufman** [comment]
@rombert Did the patch end up working for you?

**Comment by pgajdos** [comment]
Yes, the build is fixed, thank you.
https://build.opensuse.org/package/show/Apache:Modules/apache2-mod_pagespeed
