### ISSUE TITLE
32-bit-only compilation error in pagespeed/apache/apache_fetch.cc:197:50

### ISSUE THREAD

**Issue by rombert** [apache/incubator-pagespeed-mod#1167]
Since updating from 1.9.32.4 to 1.9.32.10 some openSuSE 32-bit builds( 13.1 and 13.2, but not 12.3 and Tumbleweed ) have started failing. The relevant snippet is bellow.

```
[  577s]   CXX(target) out/Release/obj.target/test_util/net/instaweb/http/mock_url_fetcher.o
[  579s] pagespeed/apache/apache_fetch.cc: In member function 'virtual bool net_instaweb::ApacheFetch::HandleWrite(const StringPiece&, net_instaweb::MessageHandler*)':
[  579s] pagespeed/apache/apache_fetch.cc:197:50: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'base::internal::StringPieceDetail<std::basic_string<char> >::size_type {aka unsigned int}' [-Werror=format=]
[  579s]                     sp.size(), mapped_url_.c_str());
[  579s]                                                   ^
[  579s]   CXX(target) out/Release/obj.target/test_util/net/instaweb/http/log_record_test_helper.o
[  580s] cc1plus: all warnings being treated as errors
[  580s] net/instaweb/instaweb_apr.target.mk:355: recipe for target 'out/Release/obj.target/instaweb_apr/pagespeed/apache/apache_fetch.o' failed
[  580s] make: *** [out/Release/obj.target/instaweb_apr/pagespeed/apache/apache_fetch.o] Error 1
[  580s] make: *** Waiting for unfinished jobs....
[  585s] error: Bad exit status from /var/tmp/rpm-tmp.NuXJLK (%build)
```

**Comment by crowell** [comment]
relevant code

``` c
  handler->Message(kWarning,
                   "Write of %ld bytes for url %s received after "
                   "being abandoned for timing out.",
                   sp.size(), mapped_url_.c_str());
```

i'm confused, the %ld should relate to `sp.size()` which returns a `StringPiece::size_type`.

What is the compiler and version on 13.1 and 13.2

**Comment by crowell** [comment]
nevermind, i read that improperly, I see the issue. Thanks!

**Comment by crowell** [comment]
@rombert applying this diff should fix the error for you.

``` diff
commit 78abd0c4b9fc3852781a1062f01cc157f8b21356
Author: Jeffrey Crowell <jcrowell@google.com>
Date:   Tue Nov 3 16:39:55 2015 -0500

    fix format type mismatch, closes #1167

    %ld doesn't match with a size_t on 32bit

diff --git a/pagespeed/apache/apache_fetch.cc b/pagespeed/apache/apache_fetch.cc
index 17c76df..5c65fb9 100644
--- a/pagespeed/apache/apache_fetch.cc
+++ b/pagespeed/apache/apache_fetch.cc
@@ -192,7 +192,7 @@ bool ApacheFetch::HandleWrite(const StringPiece& sp, MessageHandler* handler) {
     }
   }
   handler->Message(kWarning,
-                   "Write of %ld bytes for url %s received after "
+                   "Write of %zu bytes for url %s received after "
                    "being abandoned for timing out.",
                    sp.size(), mapped_url_.c_str());
   return false;  // Drop the write.
```

**Comment by rombert** [comment]
Applied, thank you!
