### ISSUE TITLE
build on ubuntu 12.04 failing

### ISSUE THREAD

**Issue by crowell** [apache/incubator-pagespeed-mod#1130]
```
out/Release/obj/gen/data2c_out/instaweb/pagespeed/opt/mobilize/xhr_opt_out.cc
  CXX(target) out/Release/obj.target/instaweb_mobilize_xhr_js_opt_data2c/gen/data2c_out/instaweb/pagespeed/opt/mobilize/xhr_opt_out.o
  AR(target) out/Release/obj.target/pagespeed/libinstaweb_mobilize_xhr_js_opt_data2c.a
  CXX(target) out/Release/obj.target/instaweb_rewriter/net/instaweb/rewriter/add_head_filter.o
  CXX(target) out/Release/obj.target/instaweb_rewriter/net/instaweb/rewriter/add_ids_filter.o
In file included from ./net/instaweb/rewriter/public/rewrite_driver.h:26:0,
                 from ./net/instaweb/rewriter/public/add_ids_filter.h:25,
                 from net/instaweb/rewriter/add_ids_filter.cc:20:
third_party/chromium/src/base/logging.h: In function â€˜std::string* logging::CheckLTImpl(const t1&, const t2&, const char*) [with t1 = int, t2 = long unsigned int, std::string = std::basic_string<char>]â€™:
net/instaweb/rewriter/add_ids_filter.cc:148:5:   instantiated from here
third_party/chromium/src/base/logging.h:559:1: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
cc1plus: all warnings being treated as errors
make: *** [out/Release/obj.target/instaweb_rewriter/net/instaweb/rewriter/add_ids_filter.o] Error 1
travis_time:end:055782ee:start=1441049351434412284,finish=1441050180668693530,duration=829234281246
```

``` sh
export CXX=g++
$ export CC=gcc
$ gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

from log here: https://s3.amazonaws.com/archive.travis-ci.org/jobs/78102537/log.txt

The issue is in the chromium logger header, so setting sign-compare to be a warning instead of an error seems like a solution.

**Comment by crowell** [comment]
builds work with clang defaults on ubuntu 12.04, i'll get to this shortly.

**Comment by crowell** [comment]
closed with https://github.com/pagespeed/mod_pagespeed/commit/fdd54f9b3348dd6fea99c0840d91d8c5c765d443
